version: "3.7"
services:
  db:
    image: mysql/mysql-server:5.7
    hostname: dbserver
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "password"

  prod:
    image: veronicaaxelsson/microblog:1.0.0-prod
    ports:
      - 8000:5000
    links:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://microblog:password@dbserver/microblog

  test:
    image: veronicaaxelsson/microblog:test
    volumes:
      - ".:/home/microblog"
