---
- name: copy Docker Compose files
  template:
    src: docker-compose.yml
    dest: ./docker-compose.yml

- name: copy Grafana.ini
  copy:
    src: grafana.ini
    dest: ./grafana.ini

- name: copy Prometheus config file
  template:
    src: prometheus.yml
    dest: ./prometheus.yml

- name: deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: ./
    files:
      - docker-compose.yml

- name: Add Prometheus as data source
  community.grafana.grafana_datasource:
    name: prometheus
    url: http://0.0.0.0:3000
    ds_type: prometheus
    ds_url: http://prometheus:9090

- name: Add Node exporter as dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://0.0.0.0:3000
    grafana_user: "admin"
    grafana_password: "admin"
    dashboard_id: 1860
    dashboard_revision: 22
