---
- name: install packages required by docker
  apt:
    update_cache: yes
    state: latest
    name:
      - gpg-agent
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
    state: present

- name: Update apt and install docker-ce
  apt:
    state: latest
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    state: present

- name: Install Docker Module for Python
  pip:
    name: docker
