---
- name: Remove image
  docker_image:
    name: "{{ image_name }}"
    state: absent
    force_absent: yes

- name: Pull mysql image and launch container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    env:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "password"
    state: started
    pull: yes
    restart_policy: always
    ports:
      - "3306:3306"
